# Generated by Django 6.0 on 2026-06-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phonr',
            new_name='phone',
        ),
    ]
