# Generated by Django 6.0 on 2026-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackusers', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
